apiVersion: v1
kind: Template
labels:
  application: jmeter-controller-job-template
metadata:
  name: jmeter-controller-job-template
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: jmeter-controller-job-${TIMESTAMP}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: jmeter-controller-job
      spec:
        containers:
        - env:
          - name: JMETER_SLAVES
            value: ${REMOTE_SERVERS_LIST}
          - name: TEST_PLAN_URL
            value: ${TEST_PLAN_URL}
          image: docker-registry.default.svc:5000/jmeter-v2/jmeter-controller
          name: jmeter-controller-job
        restartPolicy: Never
parameters:
- description: Test plan url
  name: TEST_PLAN_URL
  required: true
  value:
- description: List of remote jmeter servers
  name: REMOTE_SERVERS_LIST
  required: true
  value:
- description: Timestamp for the job
  name: TIMESTAMP
  required: true
  value:
