apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-controller-job
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: jmeter-controller-job
    spec:
      containers:
      - name: jmeter-controller-job      
        image: 172.30.1.1:5000/jmeter/jmeter-controller
        volumeMounts:
        - name: config-volume
          mountPath: /tmp                  
      volumes:
        - name: config-volume
          configMap:
            name: jmeter-test        
      restartPolicy: Never