apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2018-04-19T23:10:30Z
  generation: 12
  labels:
    app: jmeter-controller
  name: jmeter-controller
  namespace: jmeter
  resourceVersion: "84260"
  selfLink: /oapi/v1/namespaces/jmeter/deploymentconfigs/jmeter-controller
  uid: daa1aa24-4426-11e8-b9d9-b6aeaec4105c
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    app: jmeter-controller
    deploymentconfig: jmeter-controller
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: jmeter-controller
        deploymentconfig: jmeter-controller
    spec:
      containers:
      - env:
        - name: PROJECT_PATH
          value: /tmp/jmeter.jmx
        - name: JMETER_SLAVES
          value: 172.17.0.72
        image: 172.30.1.1:5000/jmeter/jmeter-controller@sha256:a09f6c67b3aafe45fecc365e63f286afaf7f6a2115867562633c462840b1c4a5
        imagePullPolicy: Always
        name: jmeter-controller
        ports:
        - containerPort: 60000
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: volume-jh8ia
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: jmeter-test
        name: volume-jh8ia
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - jmeter-controller
      from:
        kind: ImageStreamTag
        name: jmeter-controller:latest
        namespace: jmeter
      lastTriggeredImage: 172.30.1.1:5000/jmeter/jmeter-controller@sha256:a09f6c67b3aafe45fecc365e63f286afaf7f6a2115867562633c462840b1c4a5
    type: ImageChange
status:
  availableReplicas: 0
  conditions:
  - lastTransitionTime: 2018-04-19T23:52:03Z
    lastUpdateTime: 2018-04-19T23:52:03Z
    message: Deployment config does not have minimum availability.
    status: "False"
    type: Available
  - lastTransitionTime: 2018-04-19T23:58:22Z
    lastUpdateTime: 2018-04-19T23:58:22Z
    message: replication controller "jmeter-controller-10" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 10
  observedGeneration: 12
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
