apiVersion: v1
kind: Template
labels:
  application: jmeter-controller-job-template
metadata:
  name: jmeter-controller-job-template
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: jmeter-controller-job-${TIMESTAMP}
  spec:
    parallelism: 1
    completions: 1
    template:
      metadata:
        name: jmeter-controller-job
      spec:
        containers:
        - env:
          - name: JMETER_SLAVES
            value: ${REMOTE_SERVERS_LIST}
          - name: TEST_PLAN_URL
            value: ${TEST_PLAN_URL}
          - name: APPLICATION_NAME
            value: ${APPLICATION_NAME}
          - name: JENKINS_PIPELINE_RETURN_URL
            value: ${JENKINS_PIPELINE_RETURN_URL}
          - name: JENKINS_USER
            value: ${JENKINS_USER}
          - name: JENKINS_PASS
            value: ${JENKINS_PASS}
          image: ${IMAGE}
          name: jmeter-controller-job
        restartPolicy: Never
parameters:
- description: Test plan url
  name: TEST_PLAN_URL
  required: true
  value:
- description: List of remote jmeter servers
  name: REMOTE_SERVERS_LIST
  required: true
  value:
- description: Timestamp for the job
  name: TIMESTAMP
  required: true
  value:
- description: Name of the application
  name: APPLICATION_NAME
  required: true
  value:
- description: Jenkins callback URL
  name: JENKINS_PIPELINE_RETURN_URL
  required: true
  value:
- description: Jenkins Username for callback
  name: JENKINS_USER
  required: true
  value:
- description: Jenkins Password or token for callback
  name: JENKINS_PASS
  required: true
  value:
- description: JMeter image from specific cluster/project
  name: IMAGE
  required: true
